In [1]:
import numpy as np

In [2]:
np.array([10,20,30,34,22])

array([10, 20, 30, 34, 22])

In [3]:
a=np.array([10,20,30,40,50,6040,330])
a[4]

50

In [5]:
a[3:]

array([  40,   50, 6040,  330])

In [6]:
a[3:7]

array([  40,   50, 6040,  330])

In [7]:
a[1::4]

array([  20, 6040])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
ones=np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
type(np.ones)

function

In [ ]:
type(ones[3])

In [15]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [19]:
b=np.array([['x','y','z'],['a','b','c']])   
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


numpy.ndarray

In [21]:
b.ndim

2

In [22]:
c=[12,4,10,40,2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [25]:
    cabecera=[('nombre','S10'),('edad',int)]
    datos=[('Juan',10),('Maria',70),('Javier',42),('Samuel',15)]
    usuarios= np.array(datos, dtype=cabecera)


In [31]:
print(usuarios)


[(b'Juan', 10) (b'Maria', 70) (b'Javier', 42) (b'Samuel', 15)]


In [34]:
np.sort(usuarios,order='edad')



array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [35]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [38]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [39]:
np.diag ([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [40]:
headers = [('nombre','S10'), ('edad', int), ('nacionalidad','S100')]
data = [('Amelie',21,'Francesa'), 
         ('Valerie', 30,'Canadiense'),
         ('Valentina',25,'Inglesa'),
         ('Alejandra',22,'Cubana')]
users = np.array(data,dtype=headers)
np.sort(users, order = 'nacionalidad')

array([(b'Valerie', 30, b'Canadiense'), (b'Alejandra', 22, b'Cubana'),
       (b'Amelie', 21, b'Francesa'), (b'Valentina', 25, b'Inglesa')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('nacionalidad', 'S100')])

In [42]:
cabeceras = [('Name', 'S10'), ('Age', int), ('Country', 'S10')]
datos = [('Juan', 10, 'Colombia'), ('Maria', 70, 'Argentina'), ('Javier', 42, 'Ecuador'), ('Samuel', 15, 'Argelia')]
usuarios = np.array(datos, dtype = cabeceras)
np.sort(usuarios, order = 'Country')



array([(b'Samuel', 15, b'Argelia'), (b'Maria', 70, b'Argentina'),
       (b'Juan', 10, b'Colombia'), (b'Javier', 42, b'Ecuador')],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Country', 'S10')])

In [43]:
import pandas as pd

In [44]:
df = pd.DataFrame()
df['Name'] = datos[0]
df['Age'] = datos[1]
df['Country'] = datos[2]